# Generated by Django 5.1.7 on 2025-04-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpverification",
            name="otp",
            field=models.CharField(max_length=64),
        ),
    ]
