# Generated by Django 5.1.7 on 2025-04-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_otpverification_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="year",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not Applicable"),
                    ("I", "First Year"),
                    ("II", "Second Year"),
                    ("III", "Third Year"),
                    ("IV", "Fourth Year"),
                ],
                max_length=4,
                null=True,
            ),
        ),
    ]
