# Generated by Django 5.1.7 on 2025-04-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_question_quiz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="correct_answer",
            field=models.JSONField(
                blank=True, help_text="Correct answer(s) for MCQ/TrueFalse", null=True
            ),
        ),
    ]
