# Generated by Django 5.1.7 on 2025-04-29 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0005_alter_question_correct_answer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="max_score",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="Maximum score possible for this question",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="total_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total possible score for this quiz",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="quizassignment",
            name="is_graded",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="StudentPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "max_possible_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "percentile",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("rank", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.quiz"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["student", "quiz"],
                        name="quiz_studen_student_57059f_idx",
                    ),
                    models.Index(
                        fields=["quiz", "rank"], name="quiz_studen_quiz_id_e370b5_idx"
                    ),
                    models.Index(
                        fields=["quiz", "percentile"],
                        name="quiz_studen_quiz_id_5e0f75_idx",
                    ),
                ],
                "unique_together": {("student", "quiz")},
            },
        ),
    ]
