# Generated by Django 5.1.7 on 2025-04-30 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0006_question_max_score_quiz_total_score_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizResults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_score", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "max_possible_score",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("percentile", models.DecimalField(decimal_places=2, max_digits=5)),
                ("rank", models.IntegerField()),
                (
                    "time_taken_minutes",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("submitted_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="quizassignment",
            name="question_id_legacy",
        ),
        migrations.AddField(
            model_name="quiz",
            name="is_scheduled",
            field=models.BooleanField(
                default=False,
                help_text="Whether this quiz is scheduled or available immediately",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="scheduled_end_time",
            field=models.DateTimeField(
                blank=True,
                help_text="When the quiz becomes unavailable to students",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="scheduled_start_time",
            field=models.DateTimeField(
                blank=True,
                help_text="When the quiz becomes available to students",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="time_limit_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                default=30,
                help_text="Time limit in minutes for each student to complete the quiz",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="quizassignment",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="quiz.question"
            ),
        ),
        migrations.AddIndex(
            model_name="quiz",
            index=models.Index(
                fields=["scheduled_start_time", "scheduled_end_time"],
                name="quiz_quiz_schedul_2b7dbe_idx",
            ),
        ),
        migrations.AddField(
            model_name="quizresults",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="quiz.quiz"
            ),
        ),
        migrations.AddField(
            model_name="quizresults",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="quizresults",
            index=models.Index(
                fields=["quiz", "rank"], name="quiz_quizre_quiz_id_29eda9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quizresults",
            index=models.Index(
                fields=["quiz", "percentile"], name="quiz_quizre_quiz_id_39bb1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quizresults",
            index=models.Index(
                fields=["student", "quiz"], name="quiz_quizre_student_52a24d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="quizresults",
            unique_together={("quiz", "student")},
        ),
    ]
